In [125]:
#Gerekli kütüphaneler
from sklearn.linear_model import LinearRegression
import pandas as pd

In [126]:
#Veri setimizi çağıralım
df = pd.read_csv("Student_Marks.csv")

In [127]:
#Veri seti bilgisi
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   number_courses  100 non-null    int64  
 1   time_study      100 non-null    float64
 2   Marks           100 non-null    float64
dtypes: float64(2), int64(1)
memory usage: 2.5 KB
None


In [128]:
#Verileri gözden geçirelim
df.head(5)

number_courses  time_study   Marks
0               3       4.508  19.202
1               4       0.096   7.734
2               4       3.133  13.811
3               6       7.909  53.018
4               8       7.811  55.299

In [129]:
#Bağımsız değişkenleri tanımlayalım
y = df[["Marks"]]
x = df[["number_courses", "time_study"]]

In [130]:
#Lineer Regression Modelini Oluşturalım
l = LinearRegression()
#Modeli eğitelim
model = l.fit(x.values,y.values)

In [131]:
#Katsayılar
model.coef_

array([[1.86405074, 5.39917879]])

In [132]:
#Sabit
model.intercept_

array([-7.45634623])

In [133]:
'''Tahminde bulunalım 
(Günde 4 saat ders çalışan 4. sınıf öğrencisi tahmini ne kadar not alır)'''
model.predict([[4,5]])

array([[26.99575068]])

In [134]:
#Sağlamasını yapalım
(4*1.86405074)+(5*5.39917879)+(-7.45634623)

26.99575068

In [ ]:
#Hata payı ve doğruluk skoru
df.head(1)

number_courses  time_study   Marks
0               3       4.508  19.202

In [ ]:
#Tablodaki ilk öğrenciyi hesaplayalım
s1 = model.predict([[3,4.508]])[0][0] 
print(s1)

22.47530397094242


In [137]:
# 3. sınıfa giden ve günde 4.508 saat çalışan bir öğrencinin 22.475 puan alması gerekirken 19.202 puan almış. 
# Buna göre hata payı hesabımızı yapalım.

In [138]:
#Hata payı hesabı
(19.202-s1)/19.202

np.float64(-0.17046682485899478)

In [139]:
#Modelin doğruluk skoru
model.score(x.values,y.values)

0.9403656320238896